name: TJ Nealy
favicon: null
layout_spectrum: 0.99326
typography_spectrum: 0.10309
title: THIS... Is Me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9406322096474469
  lightness: 0.14276024443097413
  saturation: 0.6594113311730325
  rhythmicContrast: 0.4125962466932833
purpose: []
