name: TJMG - Beauty+ Initiative
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56845
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: '#Beauty+'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.625
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
