name: TJ Nealy
favicon: null
layout_spectrum: 0.99326
typography_spectrum: 0.10309
title: THIS... Is Me.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#1a181b'
    - '#756d6a'
    - '#ded1af'
    - '#b8916a'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.6594113311730325
  rhythmicContrast: 0.75
purpose: []
